### ISSUE TITLE
Make Anki cards without the links from the Pixiv dictionary

### ISSUE THREAD

**Issue by Wyzmic** [MarvNC/yomichan-dictionaries#31]
![image](https://github.com/MarvNC/yomichan-dictionaries/assets/72083780/d2220223-4c0c-4051-8b59-ef0647a724f3)
How could I make it so these links turn into plain text when making a flashcard? If I accidentally tap one of them they redirect me to a nonexistent page asides from the 続きを読む one.

**Comment by MarvNC** [comment]
Try adding this to your Anki styling.
```css
span.gloss-sc-span[data-sc-pixiv='nav-header'],
div.gloss-sc-div[data-sc-pixiv='related-tags'] {
  display: none;
}
```
Each section is semantically labeled somewhat so you can style it as you wish to remove/change elements.
